//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterio
    {
        public string id_criterio { get; set; }
        public string contexto { get; set; }
        public string resultado { get; set; }
        public string evento { get; set; }
        public string historia_FK { get; set; }
    
        public virtual Historia Historia { get; set; }
    }
}
