//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progreso
    {
        public string id_progreso { get; set; }
        public int porcentaje { get; set; }
        public System.DateTime fecha { get; set; }
        public string tarea_FK { get; set; }
    
        public virtual Tarea Tarea { get; set; }
    }
}
