//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sprint()
        {
            this.Historia = new HashSet<Historia>();
        }
    
        public string id_sprint { get; set; }
        public int numero { get; set; }
        public System.DateTime fecha_in { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> puntos_totales { get; set; }
        public string proyecto_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historia> Historia { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
