//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public string id_telefono { get; set; }
        public string telefono1 { get; set; }
        public string email_FK { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
